services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/audio_files
    env_file: .env
    command: >
      sh -c "alembic upgrade head && uvicorn app.entrypoint.main:create_fastapi_app --factory --reload --host 0.0.0.0 --port 8000"
    depends_on:
      - db_postgres
    ports:
      - "8000:8000"
    networks:
      - app_network
    restart: always

  db_postgres:
    container_name: db_postgres
    image: postgres:16.2-alpine
    restart: unless-stopped
    env_file: .env
    networks:
      - app_network
    volumes:
      - audio_files_db:/var/lib/postgresql/data/

volumes:
  audio_files_db:

networks:
  app_network: